from __future__ import annotations

import argparse
import os
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Train a YOLO face detector on the prepared WIDER Face dataset.")
    parser.add_argument(
        "--data",
        default="backend/runtime/datasets/wider_face/prepared/wider_face_yolo.yaml",
        help="Path to the YOLO data.yaml generated by prepare_wider_face.py.",
    )
    parser.add_argument("--model", default="yolov8n.pt", help="Ultralytics model checkpoint or model yaml.")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default=None, help="Training device, for example 0, cpu, or 0,1.")
    parser.add_argument("--workers", type=int, default=0, help="Data loader workers. Keep 0 on Windows for smoke tests.")
    parser.add_argument("--fraction", type=float, default=1.0, help="Fraction of the training set to use.")
    parser.add_argument("--project", default="backend/runtime/training")
    parser.add_argument("--name", default="wider_face_yolo")
    args = parser.parse_args()

    data_path = Path(args.data).resolve()
    if not data_path.exists():
        raise FileNotFoundError(f"Prepared YOLO data file not found: {data_path}")
    runtime_config = Path("backend/runtime/ultralytics").resolve()
    matplotlib_config = Path("backend/runtime/matplotlib").resolve()
    runtime_config.mkdir(parents=True, exist_ok=True)
    matplotlib_config.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("YOLO_CONFIG_DIR", str(runtime_config))
    os.environ.setdefault("MPLCONFIGDIR", str(matplotlib_config))

    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise SystemExit(
            "Ultralytics is not installed in this Python environment. "
            "Install it first, then rerun this script: pip install ultralytics"
        ) from exc

    model = YOLO(args.model)
    train_kwargs = {
        "data": str(data_path),
        "epochs": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "workers": args.workers,
        "fraction": args.fraction,
        "project": str(Path(args.project).resolve()),
        "name": args.name,
    }
    if args.device:
        train_kwargs["device"] = args.device
    model.train(**train_kwargs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
