"""Admit VISION as an observation method.

`ObservationMethod.VISION` was added to the model when the vision layer was
built, but the CHECK constraint on `observations.method` was frozen into the
evidence-schema migration before it existed. The result is a vocabulary that the
code can produce and the database refuses: every observation the vision stage
tried to write against a migrated database failed with

    IntegrityError: CHECK constraint failed: ck_observations_method_valid

The test suite could not see this. Tests build their schema from
`Base.metadata`, which carries the current enum; deployments build theirs from
these migrations, which carried the old one. Anything the two disagree about is
invisible until it reaches a real database — so this revision closes the gap,
and `tests/integration/test_migrations.py` now compares the two build paths so
the next divergence fails a test instead of a request.

Revision ID: b8f0d1c94a27
Revises: d25970cbecf4
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b8f0d1c94a27"
down_revision: str | None = "d25970cbecf4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Mirrors database.base.NAMING_CONVENTION. Copied rather than imported: a
# migration describes the schema as it was at a point in time, and importing
# live application code would make old revisions change meaning when that code
# is edited.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

METHODS_BEFORE = (
    "CAPTION",
    "META",
    "NER",
    "OCR",
    "OPENGRAPH",
    "PROVIDER",
    "REGEX",
    "SCHEMA_ORG",
    "TITLE",
)
METHODS_AFTER = tuple(sorted((*METHODS_BEFORE, "VISION")))


def _method(methods: tuple[str, ...]) -> sa.Enum:
    """The column type. The CHECK is generated by this type and owned by it —
    which is why the vocabulary is changed by replacing the type rather than by
    dropping a constraint."""
    return sa.Enum(
        *methods, name="method_valid", native_enum=False, create_constraint=True
    )


def _observations(methods: tuple[str, ...]) -> sa.Table:
    """The `observations` table with `methods` as its method vocabulary.

    Spelled out in full because SQLite cannot alter a CHECK constraint in place:
    the table is rebuilt, and SQLAlchemy does not reflect CHECK constraints from
    SQLite. Without `copy_from` giving batch mode an accurate picture, the
    rebuild would quietly drop `ck_observations_machine_origin_only` — the
    constraint that keeps a human from hand-writing an "extracted" observation.
    """
    metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)
    return sa.Table(
        "observations",
        metadata,
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin", sa.String(length=24), server_default="EXTRACTED", nullable=False
        ),
        sa.Column("method", _method(methods), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=False),
        sa.Column("extractor_version", sa.String(length=64), nullable=False),
        sa.Column("method_confidence", sa.Float(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("origin = 'EXTRACTED'", name="machine_origin_only"),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name="fk_observations_image_id_images",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_observations_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name="fk_observations_page_id_pages",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_observations"),
        sa.Index("ix_observations_investigation_page", "investigation_id", "page_id"),
        sa.Index("ix_observations_normalized", "normalized_value"),
    )


def _revocabulary(current: tuple[str, ...], target: tuple[str, ...]) -> None:
    """Swap the method vocabulary from `current` to `target`.

    The two dialects need different operations and get them, rather than one
    path that happens to work on the machine it was written on.
    """
    if op.get_bind().dialect.name == "sqlite":
        # SQLite cannot alter a CHECK in place, so the table is rebuilt. The
        # constraint is type-bound — batch mode skips it deliberately — which
        # means the way to change it is to replace the column's type and let the
        # new one carry its own CHECK.
        with op.batch_alter_table(
            "observations", copy_from=_observations(current), recreate="always"
        ) as batch:
            batch.alter_column(
                "method",
                existing_type=_method(current),
                type_=_method(target),
                existing_nullable=False,
            )
        return

    # PostgreSQL alters the CHECK directly — no rewrite, which is the whole
    # reason DATA_MODEL §9 chose VARCHAR + CHECK over a native enum type.
    # `op.f` marks the name as final; without it the naming convention is
    # applied to a name that already carries it.
    op.drop_constraint(
        op.f("ck_observations_method_valid"), "observations", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_observations_method_valid"),
        "observations",
        sa.column("method").in_(target),
    )


def upgrade() -> None:
    _revocabulary(METHODS_BEFORE, METHODS_AFTER)


def downgrade() -> None:
    """Narrow the vocabulary again — refusing rather than deleting evidence.

    Observations are evidence. A downgrade that silently dropped every VISION
    row to satisfy the narrower constraint would destroy records an
    investigation may depend on, so it stops and says what is in the way.
    """
    remaining = op.get_bind().execute(
        sa.text("SELECT count(*) FROM observations WHERE method = 'VISION'")
    ).scalar_one()
    if remaining:
        raise RuntimeError(
            f"{remaining} VISION observation(s) exist. Downgrading would make them "
            "unrepresentable. Export or delete them deliberately first — this "
            "migration will not discard evidence on your behalf."
        )
    _revocabulary(METHODS_AFTER, METHODS_BEFORE)
