"""federated imatch identity

Revision ID: d25970cbecf4
Revises: ecd33abc8611
Create Date: 2026-08-03 04:35:16.022280
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd25970cbecf4'
down_revision: str | None = 'ecd33abc8611'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_subject', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('external_tenant', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_external_subject'), ['external_subject'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_external_subject'), type_='unique')
        batch_op.drop_column('external_tenant')
        batch_op.drop_column('external_subject')

    # ### end Alembic commands ###
