"""evidence schema

Revision ID: ecd33abc8611
Revises: f12b5f10cba9
Create Date: 2026-08-03 03:31:02.533524
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ecd33abc8611'
down_revision: str | None = 'f12b5f10cba9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Full-text search is PostgreSQL-only. SQLite has FTS5 but it is a virtual
# table with different semantics, and the test suite exercises search through
# the repository rather than the index, so the guard is a dialect check rather
# than a parallel implementation.
def _install_fulltext() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # Generated column: one index serves every object type, and ranking is
    # therefore comparable across cases, pages, entities and notes.
    # 'simple' rather than 'english': an OSINT corpus is multilingual, and
    # English stemming would mangle names, which are the primary search target.
    op.execute(
        """
        ALTER TABLE search_documents
        ADD COLUMN tsv tsvector
        GENERATED ALWAYS AS (
            setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('simple', coalesce(body,  '')), 'B')
        ) STORED;
        """
    )
    op.execute("CREATE INDEX ix_search_documents_tsv ON search_documents USING gin (tsv);")
    op.execute(
        "CREATE INDEX ix_search_documents_title_trgm "
        "ON search_documents USING gin (title gin_trgm_ops);"
    )
    # Fuzzy entity-name matching for the correlation UI.
    op.execute(
        "CREATE INDEX ix_entities_canonical_name_trgm "
        "ON entities USING gin (canonical_name gin_trgm_ops);"
    )


def _remove_fulltext() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("DROP INDEX IF EXISTS ix_entities_canonical_name_trgm;")
    op.execute("DROP INDEX IF EXISTS ix_search_documents_title_trgm;")
    op.execute("DROP INDEX IF EXISTS ix_search_documents_tsv;")
    op.execute("ALTER TABLE search_documents DROP COLUMN IF EXISTS tsv;")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registrable_domain', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.Enum('ARCHIVE', 'BLOG', 'COMPANY', 'DOCUMENTATION', 'EDUCATIONAL', 'FORUM', 'GOVERNMENT', 'NEWS', 'SOCIAL_MEDIA', 'UNKNOWN', name='classification_valid', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('classification_basis', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains')),
    sa.UniqueConstraint('registrable_domain', name=op.f('uq_domains_registrable_domain'))
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('ENTITY', 'FACT', 'IMAGE', 'OBSERVATION', 'PAGE', 'TIMELINE_EVENT', name='target_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_bookmarks_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_bookmarks_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks')),
    sa.UniqueConstraint('owner_id', 'target_type', 'target_id', name='uq_bookmark_target')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_checklists_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists'))
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('copilot_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_copilot_sessions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copilot_sessions'))
    )
    with op.batch_alter_table('copilot_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_sessions_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DOCUMENT', 'EMAIL', 'EVENT', 'LANDMARK', 'LOCATION', 'ORGANIZATION', 'PERSON', 'PHONE', 'PRODUCT', 'USERNAME', 'VEHICLE', 'WEBSITE', name='type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('verification_state', sa.Enum('HUMAN_CONFIRMED', 'HUMAN_REJECTED', 'MACHINE_PROPOSED', name='verification_valid', native_enum=False, create_constraint=True), server_default='MACHINE_PROPOSED', nullable=False),
    sa.Column('possible_duplicate_of', sa.Uuid(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_entities_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['possible_duplicate_of'], ['entities.id'], name=op.f('fk_entities_possible_duplicate_of_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('investigation_id', 'type', 'normalized_key', name='uq_entities_identity')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_investigation_type', ['investigation_id', 'type'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=24), server_default='HUMAN', nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_richtext', sa.JSON(), nullable=False),
    sa.Column('body_plain', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("origin = 'HUMAN'", name=op.f('ck_notes_human_origin_only')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_notes_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_investigation', ['investigation_id'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('site_name', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('author_raw', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_simhash', sa.String(length=16), nullable=True),
    sa.Column('raw_html_key', sa.Text(), nullable=False),
    sa.Column('screenshot_key', sa.Text(), nullable=False),
    sa.Column('text_content_key', sa.Text(), nullable=False),
    sa.Column('outbound_links', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=False),
    sa.Column('observable', sa.Boolean(), nullable=False),
    sa.Column('progress_state', sa.Enum('DISCOVERED', 'DOWNLOADED', 'INCLUDED_IN_REPORT', 'REVIEWED', 'VERIFIED', name='progress_valid', native_enum=False, create_constraint=True), server_default='DISCOVERED', nullable=False),
    sa.Column('retention_state', sa.Enum('ACTIVE', 'ARCHIVED', 'PURGED', 'RETAINED', name='retention_valid', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_pages_domain_id_domains')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_pages_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('investigation_id', 'url', name='uq_pages_investigation_url')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index('ix_pages_domain', ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_pages_simhash', ['content_simhash'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('HTML', 'JSON', 'MARKDOWN', 'PDF', name='format_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_reports_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('CONFLICT', 'DUPLICATE_MERGE', 'ENTITY_CANDIDATE', 'FACT_CANDIDATE', 'PROVENANCE_CLASS', name='kind_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'DEFERRED', 'PENDING', 'REJECTED', name='status_valid', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_review_items_decided_by_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_review_items_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index('ix_review_queue', ['investigation_id', 'status', 'priority'], unique=False)

    op.create_table('search_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('object_type', sa.Enum('CASE', 'DOMAIN', 'ENTITY', 'EVENT', 'FACT', 'IMAGE', 'NOTE', 'OCR_TEXT', 'PAGE', 'REPORT', name='object_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_search_documents_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_documents')),
    sa.UniqueConstraint('object_type', 'object_id', name='uq_search_object')
    )
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.create_index('ix_search_investigation', ['investigation_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checklist_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('fk_checklist_items_checklist_id_checklists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items'))
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('content_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('original_page_id', sa.Uuid(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_content_clusters_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_page_id'], ['pages.id'], name=op.f('fk_content_clusters_original_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_clusters'))
    )
    with op.batch_alter_table('content_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_clusters_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('copilot_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('assistant', 'user', name='role_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.Enum('PASSED', 'PENDING', 'REJECTED', name='validation_valid', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('rejected_spans', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['copilot_sessions.id'], name=op.f('fk_copilot_messages_session_id_copilot_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copilot_messages'))
    )
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_messages_session_id'), ['session_id'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('surface_form', sa.String(length=500), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_aliases_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_id', 'surface_form', name='uq_entity_alias')
    )
    op.create_table('facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('COMMON', 'CONFLICTED', 'UNIQUE', 'UNKNOWN', name='status_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('conflict_group_id', sa.Uuid(), nullable=True),
    sa.Column('classification', sa.Enum('DISPUTED', 'NEEDS_REVIEW', 'REJECTED', 'UNVERIFIED', 'VERIFIED', name='classification_valid', native_enum=False, create_constraint=True), server_default='UNVERIFIED', nullable=False),
    sa.Column('classified_by', sa.Uuid(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification_note', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'LOW', 'MEDIUM', 'UNCERTAIN', name='confidence_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_explanation', sa.JSON(), nullable=False),
    sa.Column('confidence_factor_count', sa.Integer(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_asserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scorer_version', sa.String(length=64), nullable=False),
    sa.CheckConstraint('confidence_factor_count >= 1', name=op.f('ck_facts_explanation_required')),
    sa.ForeignKeyConstraint(['classified_by'], ['users.id'], name=op.f('fk_facts_classified_by_users')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_facts_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_facts_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts'))
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index('ix_facts_conflict_group', ['conflict_group_id'], unique=False)
        batch_op.create_index('ix_facts_entity', ['entity_id'], unique=False)
        batch_op.create_index('ix_facts_investigation_status', ['investigation_id', 'status'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('node_type', sa.Enum('ARCHIVE', 'ARTICLE', 'DOCUMENT', 'DOMAIN', 'EVENT', 'IMAGE', 'LOCATION', 'ORGANIZATION', 'PAGE', 'PERSON', 'SOCIAL_PROFILE', name='node_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ref_table', sa.String(length=60), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('asserted_by_page_id', sa.Uuid(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.CheckConstraint("node_type <> 'PERSON' OR asserted_by_page_id IS NOT NULL", name=op.f('ck_graph_nodes_person_requires_assertion')),
    sa.ForeignKeyConstraint(['asserted_by_page_id'], ['pages.id'], name=op.f('fk_graph_nodes_asserted_by_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_graph_nodes_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('investigation_id', 'node_type', 'ref_id', name='uq_graph_node_identity')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_graph_nodes_investigation_type', ['investigation_id', 'node_type'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('DISCOVERED', 'PROBE', name='role_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('dhash', sa.String(length=16), nullable=True),
    sa.Column('whash', sa.String(length=16), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('exif', sa.JSON(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_image_url', sa.Text(), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_state', sa.Enum('DISCOVERED', 'DOWNLOADED', 'INCLUDED_IN_REPORT', 'REVIEWED', 'VERIFIED', name='progress_valid', native_enum=False, create_constraint=True), server_default='DISCOVERED', nullable=False),
    sa.Column('retention_state', sa.Enum('ACTIVE', 'ARCHIVED', 'PURGED', 'RETAINED', name='retention_valid', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_images_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], name=op.f('fk_images_source_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_images_investigation_role', ['investigation_id', 'role'], unique=False)
        batch_op.create_index('ix_images_phash', ['phash'], unique=False)
        batch_op.create_index('ix_images_sha256', ['sha256'], unique=False)

    op.create_table('note_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_attachments_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_attachments'))
    )
    with op.batch_alter_table('note_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_attachments_note_id'), ['note_id'], unique=False)

    op.create_table('note_links',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("target_type IN ('FACT', 'PAGE', 'IMAGE', 'ENTITY', 'TIMELINE_EVENT', 'OBSERVATION')", name=op.f('ck_note_links_ck_note_links_target_type_valid')),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_links_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'target_type', 'target_id', name=op.f('pk_note_links'))
    )
    op.create_table('content_cluster_members',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('MIRROR', 'MODIFIED_COPY', 'ORIGINAL', 'PARTIAL_COPY', 'REPOST', 'TRANSLATION', name='role_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('role_confidence', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['content_clusters.id'], name=op.f('fk_content_cluster_members_cluster_id_content_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_content_cluster_members_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'page_id', name=op.f('pk_content_cluster_members'))
    )
    op.create_table('discovery_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_version', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.Enum('ARCHIVE_LOOKUP', 'CONTENT_SOURCE', 'IMAGE_DISCOVERY', 'PAGE_METADATA', name='capability_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('probe_image_id', sa.Uuid(), nullable=True),
    sa.Column('query_parameters', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_response_key', sa.Text(), nullable=False),
    sa.Column('results_returned', sa.Integer(), nullable=False),
    sa.Column('results_accepted', sa.Integer(), nullable=False),
    sa.Column('results_rejected', sa.Integer(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_discovery_requests_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_discovery_requests_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['probe_image_id'], ['images.id'], name=op.f('fk_discovery_requests_probe_image_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_requests'))
    )
    with op.batch_alter_table('discovery_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_requests_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.Enum('APPEARS_ON', 'ARCHIVED_AS', 'AUTHORED_BY', 'COPY_OF', 'EMPLOYED_BY', 'HOSTED_BY', 'LINKS_TO', 'LOCATED_IN', 'MENTIONS', name='edge_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('derivation', sa.Text(), nullable=False),
    sa.Column('evidence_observation_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'LOW', 'MEDIUM', 'UNCERTAIN', name='confidence_valid', native_enum=False, create_constraint=True), server_default='LOW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('json_array_length(evidence_observation_ids) >= 1', name=op.f('ck_graph_edges_edge_requires_evidence')),
    sa.ForeignKeyConstraint(['from_node_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_from_node_id_graph_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_graph_edges_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_to_node_id_graph_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges')),
    sa.UniqueConstraint('from_node_id', 'to_node_id', 'edge_type', name='uq_graph_edge_identity')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_edges_from', ['from_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graph_edges_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_graph_edges_to', ['to_node_id'], unique=False)

    op.create_table('image_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('from_image_id', sa.Uuid(), nullable=False),
    sa.Column('to_image_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.Enum('COMPRESSED_COPY', 'CROPPED_COPY', 'EXACT_COPY', 'MIRRORED_COPY', 'NEAR_DUPLICATE', 'REJECTED', 'RESIZED_COPY', 'THUMBNAIL', 'UNVERIFIED', name='relationship_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('phash_distance', sa.Integer(), nullable=True),
    sa.Column('justification', sa.JSON(), nullable=False),
    sa.Column('classifier_version', sa.String(length=64), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_image_id'], ['images.id'], name=op.f('fk_image_relationships_from_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_image_relationships_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_image_id'], ['images.id'], name=op.f('fk_image_relationships_to_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_relationships')),
    sa.UniqueConstraint('from_image_id', 'to_image_id', name='uq_image_rel_pair')
    )
    with op.batch_alter_table('image_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_relationships_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('monitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('cadence', sa.Enum('DAILY', 'MONTHLY', 'WEEKLY', name='cadence_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_monitors_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_monitors_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitors'))
    )
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.create_index('ix_monitors_due', ['enabled', 'next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitors_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('origin', sa.String(length=24), server_default='EXTRACTED', nullable=False),
    sa.Column('method', sa.Enum('CAPTION', 'META', 'NER', 'OCR', 'OPENGRAPH', 'PROVIDER', 'REGEX', 'SCHEMA_ORG', 'TITLE', name='method_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('method_confidence', sa.Float(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origin = 'EXTRACTED'", name=op.f('ck_observations_machine_origin_only')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_observations_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_observations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_observations_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_investigation_page', ['investigation_id', 'page_id'], unique=False)
        batch_op.create_index('ix_observations_normalized', ['normalized_value'], unique=False)

    op.create_table('appearances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('probe_image_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_request_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('provider_score', sa.Float(), nullable=True),
    sa.Column('provider_reported_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_result', sa.Enum('PENDING', 'REJECTED', 'UNREACHABLE', 'VERIFIED', name='verification_valid', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.ForeignKeyConstraint(['discovery_request_id'], ['discovery_requests.id'], name=op.f('fk_appearances_discovery_request_id_discovery_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_appearances_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['probe_image_id'], ['images.id'], name=op.f('fk_appearances_probe_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appearances'))
    )
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appearances_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_appearances_probe', ['probe_image_id'], unique=False)

    op.create_table('fact_evidence',
    sa.Column('fact_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name=op.f('fk_fact_evidence_fact_id_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_fact_evidence_observation_id_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', 'observation_id', name=op.f('pk_fact_evidence'))
    )
    op.create_table('mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.Enum('DOCUMENT', 'EMAIL', 'EVENT', 'LANDMARK', 'LOCATION', 'ORGANIZATION', 'PERSON', 'PHONE', 'PRODUCT', 'USERNAME', 'VEHICLE', 'WEBSITE', name='entity_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('surface_form', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_mentions_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_mentions_observation_id_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index('ix_mentions_entity', ['entity_id'], unique=False)

    op.create_table('monitor_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changes_detected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_monitor_runs_monitor_id_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_monitor_runs_pipeline_run_id_pipeline_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_runs'))
    )
    with op.batch_alter_table('monitor_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_runs_monitor_id'), ['monitor_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('precision', sa.Enum('DAY', 'EXACT', 'INFERRED', 'MONTH', 'YEAR', name='precision_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('kind', sa.Enum('ARCHIVE_SNAPSHOT', 'IMAGE_FIRST_APPEARANCE', 'INVESTIGATION_ACTION', 'LATEST_APPEARANCE', 'NEWS_PUBLICATION', 'PAGE_REMOVED', 'SITE_UPDATE', name='kind_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_observation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_observation_id'], ['observations.id'], name=op.f('fk_timeline_events_evidence_observation_id_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_timeline_events_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_timeline_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_timeline_events_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index('ix_timeline_investigation_time', ['investigation_id', 'occurred_at'], unique=False)

    op.create_table('monitor_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_run_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.Enum('ARCHIVE_ADDED', 'IMAGE_REPLACED', 'NEW_APPEARANCE', 'PAGE_REMOVED', 'PAGE_UNOBSERVABLE', 'PAGE_UPDATED', name='change_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('confirming_runs', sa.Integer(), nullable=False),
    sa.Column('timeline_event_id', sa.Uuid(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_monitor_changes_image_id_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_run_id'], ['monitor_runs.id'], name=op.f('fk_monitor_changes_monitor_run_id_monitor_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_monitor_changes_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeline_event_id'], ['timeline_events.id'], name=op.f('fk_monitor_changes_timeline_event_id_timeline_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_changes'))
    )
    with op.batch_alter_table('monitor_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_changes_monitor_run_id'), ['monitor_run_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_log_investigation_id_investigations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_audit_log_actor_id_users'), type_='foreignkey')

    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_custody_events_actor_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_custody_events_investigation_id_investigations'), type_='foreignkey')

    # ### end Alembic commands ###

    _install_fulltext()


def downgrade() -> None:
    # Indexes and the generated column must go before their tables do.
    _remove_fulltext()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_custody_events_investigation_id_investigations'), 'investigations', ['investigation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_custody_events_actor_id_users'), 'users', ['actor_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_audit_log_actor_id_users'), 'users', ['actor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_audit_log_investigation_id_investigations'), 'investigations', ['investigation_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('monitor_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_changes_monitor_run_id'))

    op.drop_table('monitor_changes')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_investigation_time')

    op.drop_table('timeline_events')
    with op.batch_alter_table('monitor_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_runs_monitor_id'))

    op.drop_table('monitor_runs')
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_mentions_entity')

    op.drop_table('mentions')
    op.drop_table('fact_evidence')
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_index('ix_appearances_probe')
        batch_op.drop_index(batch_op.f('ix_appearances_investigation_id'))

    op.drop_table('appearances')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('ix_observations_normalized')
        batch_op.drop_index('ix_observations_investigation_page')

    op.drop_table('observations')
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitors_investigation_id'))
        batch_op.drop_index('ix_monitors_due')

    op.drop_table('monitors')
    with op.batch_alter_table('image_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_relationships_investigation_id'))

    op.drop_table('image_relationships')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_edges_to')
        batch_op.drop_index(batch_op.f('ix_graph_edges_investigation_id'))
        batch_op.drop_index('ix_graph_edges_from')

    op.drop_table('graph_edges')
    with op.batch_alter_table('discovery_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_requests_investigation_id'))

    op.drop_table('discovery_requests')
    op.drop_table('content_cluster_members')
    op.drop_table('note_links')
    with op.batch_alter_table('note_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_attachments_note_id'))

    op.drop_table('note_attachments')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_sha256')
        batch_op.drop_index('ix_images_phash')
        batch_op.drop_index('ix_images_investigation_role')
        batch_op.drop_index(batch_op.f('ix_images_investigation_id'))

    op.drop_table('images')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_nodes_investigation_type')

    op.drop_table('graph_nodes')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index('ix_facts_investigation_status')
        batch_op.drop_index('ix_facts_entity')
        batch_op.drop_index('ix_facts_conflict_group')

    op.drop_table('facts')
    op.drop_table('entity_aliases')
    with op.batch_alter_table('copilot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_messages_session_id'))

    op.drop_table('copilot_messages')
    with op.batch_alter_table('content_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_clusters_investigation_id'))

    op.drop_table('content_clusters')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklist_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_search_investigation')

    op.drop_table('search_documents')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index('ix_review_queue')

    op.drop_table('review_items')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_investigation_id'))

    op.drop_table('reports')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('ix_pages_simhash')
        batch_op.drop_index(batch_op.f('ix_pages_investigation_id'))
        batch_op.drop_index('ix_pages_domain')

    op.drop_table('pages')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_investigation')

    op.drop_table('notes')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_investigation_type')

    op.drop_table('entities')
    with op.batch_alter_table('copilot_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_sessions_investigation_id'))

    op.drop_table('copilot_sessions')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_investigation_id'))

    op.drop_table('checklists')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_investigation_id'))

    op.drop_table('bookmarks')
    op.drop_table('domains')
    # ### end Alembic commands ###
