"""initial workspace audit custody

Revision ID: f12b5f10cba9
Revises: 
Create Date: 2026-08-03 03:09:46.186962
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f12b5f10cba9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables that must be insert-only. Immutability is enforced by privilege rather
# than application discipline: even a bug, a migration script, or someone at a
# psql prompt using the application role cannot rewrite history. Combined with
# the hash chain, tampering requires superuser access *and* still breaks every
# subsequent hash.
APPEND_ONLY_TABLES = ("audit_log", "custody_events")

APPLICATION_ROLE = "iie_app"


def _harden_append_only() -> None:
    """PostgreSQL only. SQLite has no role system, and test databases are
    disposable, so the guarantee is asserted in tests there instead."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # CREATE ROLE is not idempotent and the role may be provisioned externally.
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APPLICATION_ROLE}') THEN
                CREATE ROLE {APPLICATION_ROLE} NOLOGIN;
            END IF;
        END
        $$;
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(f"GRANT SELECT, INSERT ON {table} TO {APPLICATION_ROLE};")
        op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON {table} FROM {APPLICATION_ROLE};")


def _release_append_only() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for table in APPEND_ONLY_TABLES:
        op.execute(f"REVOKE ALL ON {table} FROM {APPLICATION_ROLE};")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'investigator', 'reviewer', name='role_valid', native_enum=False, create_constraint=True), server_default='investigator', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lawful_basis', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', 'DELETED_PENDING_RETENTION', 'NEW', 'UNDER_REVIEW', name='status_valid', native_enum=False, create_constraint=True), server_default='NEW', nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_investigations_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations')),
    sa.UniqueConstraint('owner_id', 'case_id', name='uq_investigations_owner_case')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index('ix_investigations_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_retention_expires_at'), ['retention_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('retention_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.Column('auto_purge', sa.Boolean(), nullable=False),
    sa.Column('export_before_purge', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('default_days >= 1', name=op.f('ck_retention_policies_ck_retention_policies_days_positive')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_retention_policies_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=80), nullable=False),
    sa.Column('lawful_basis', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_audit_log_investigation_id_investigations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_investigation', ['investigation_id', 'id'], unique=False)

    op.create_table('custody_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('EXPORT_PACKAGE', 'HTML_SNAPSHOT', 'IMAGE', 'INVESTIGATION', 'PAGE', 'REPORT', 'SCREENSHOT', name='artifact_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('COLLECTED', 'EXPORTED', 'HASHED', 'INCLUDED_IN_REPORT', 'MIGRATED', 'SCREENSHOT_CAPTURED', 'TRANSFORMED', name='action_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_kind', sa.Enum('HUMAN', 'SYSTEM', name='actor_kind_valid', native_enum=False, create_constraint=True), server_default='SYSTEM', nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_location', sa.Text(), nullable=False),
    sa.Column('transformation', sa.JSON(), nullable=False),
    sa.Column('derived_from_id', sa.Uuid(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_custody_events_actor_id_users')),
    sa.ForeignKeyConstraint(['derived_from_id'], ['custody_events.id'], name=op.f('fk_custody_events_derived_from_id_custody_events')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_custody_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custody_events')),
    sa.UniqueConstraint('artifact_type', 'artifact_id', 'sequence', name='uq_custody_artifact_sequence')
    )
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.create_index('ix_custody_artifact', ['artifact_type', 'artifact_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_custody_events_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('evidence_lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('EXPORT_PACKAGE', 'HTML_SNAPSHOT', 'IMAGE', 'INVESTIGATION', 'PAGE', 'REPORT', 'SCREENSHOT', name='artifact_type_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('axis', sa.Enum('PROGRESS', 'RETENTION', name='axis_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('from_state', sa.Enum('ACTIVE', 'ARCHIVED', 'DISCOVERED', 'DOWNLOADED', 'INCLUDED_IN_REPORT', 'PURGED', 'RETAINED', 'REVIEWED', 'VERIFIED', name='from_state_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('to_state', sa.Enum('ACTIVE', 'ARCHIVED', 'DISCOVERED', 'DOWNLOADED', 'INCLUDED_IN_REPORT', 'PURGED', 'RETAINED', 'REVIEWED', 'VERIFIED', name='to_state_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_evidence_lifecycle_events_actor_id_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_lifecycle_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_lifecycle_events'))
    )
    with op.batch_alter_table('evidence_lifecycle_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_lifecycle_events_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index('ix_lifecycle_artifact', ['artifact_type', 'artifact_id'], unique=False)

    op.create_table('investigation_status_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', 'DELETED_PENDING_RETENTION', 'NEW', 'UNDER_REVIEW', name='from_status_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('to_status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', 'DELETED_PENDING_RETENTION', 'NEW', 'UNDER_REVIEW', name='to_status_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_investigation_status_events_actor_id_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_status_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_status_events'))
    )
    with op.batch_alter_table('investigation_status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_status_events_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'MONITOR', 'RESUME', name='trigger_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'PAUSED', 'QUEUED', 'RUNNING', name='status_valid', native_enum=False, create_constraint=True), server_default='QUEUED', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_pipeline_runs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('retention_holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('EXPORT_PACKAGE', 'HTML_SNAPSHOT', 'IMAGE', 'INVESTIGATION', 'PAGE', 'REPORT', 'SCREENSHOT', name='artifact_type_valid', native_enum=False, create_constraint=True), server_default='INVESTIGATION', nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('placed_by', sa.Uuid(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_by', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_retention_holds_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], name=op.f('fk_retention_holds_placed_by_users')),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_retention_holds_released_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_holds'))
    )
    with op.batch_alter_table('retention_holds', schema=None) as batch_op:
        batch_op.create_index('ix_retention_holds_active', ['investigation_id', 'released_at'], unique=False)

    op.create_table('config_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('scorer_version', sa.String(length=64), nullable=False),
    sa.Column('classifier_version', sa.String(length=64), nullable=False),
    sa.Column('parser_versions', sa.JSON(), nullable=False),
    sa.Column('extractor_versions', sa.JSON(), nullable=False),
    sa.Column('provider_versions', sa.JSON(), nullable=False),
    sa.Column('prompt_versions', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_config_snapshots_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_config_snapshots_pipeline_run_id_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_snapshots'))
    )
    with op.batch_alter_table('config_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_snapshots_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('pipeline_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('CLASSIFY_DOMAIN', 'CLUSTER', 'CORRELATE', 'CRAWL', 'DISCOVER', 'EXTRACT', 'GRAPH', 'INGEST', 'OCR', 'PARSE', 'REPORT', 'SCORE', 'SUMMARIZE', 'TIMELINE', 'VERIFY', name='stage_valid', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'OK', 'PENDING', 'RUNNING', 'SKIPPED', name='status_valid', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_done', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_pipeline_stages_run_id_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages')),
    sa.UniqueConstraint('run_id', 'stage', name='uq_pipeline_stages_run_stage')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stages_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###

    _harden_append_only()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_run_id'))

    op.drop_table('pipeline_stages')
    with op.batch_alter_table('config_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_snapshots_investigation_id'))

    op.drop_table('config_snapshots')
    with op.batch_alter_table('retention_holds', schema=None) as batch_op:
        batch_op.drop_index('ix_retention_holds_active')

    op.drop_table('retention_holds')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_investigation_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('investigation_status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_status_events_investigation_id'))

    op.drop_table('investigation_status_events')
    with op.batch_alter_table('evidence_lifecycle_events', schema=None) as batch_op:
        batch_op.drop_index('ix_lifecycle_artifact')
        batch_op.drop_index(batch_op.f('ix_evidence_lifecycle_events_investigation_id'))

    op.drop_table('evidence_lifecycle_events')
    with op.batch_alter_table('custody_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custody_events_investigation_id'))
        batch_op.drop_index('ix_custody_artifact')

    op.drop_table('custody_events')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_investigation')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    op.drop_table('retention_policies')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_retention_expires_at'))
        batch_op.drop_index('ix_investigations_owner_status')

    op.drop_table('investigations')
    op.drop_table('users')
    # ### end Alembic commands ###

    _release_append_only()
