apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexgen-imatch-api
spec:
  rules:
    - host: api.nexgenforensics.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexgen-imatch-api
                port:
                  number: 8443
