apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexgen-identity-api-default-deny
spec:
  podSelector:
    matchLabels:
      app: nexgen-identity-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8443
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
